// AUTO-GENERATED by backend/services/journey_verifier/emitter.py
// Do not hand-edit. Regenerated on every pipeline pass.

import { defineConfig, devices } from "@playwright/test";

export default defineConfig({
  testDir: __dirname,
  testMatch: "driver.spec.ts",
  timeout: 120_000,
  expect: { timeout: 10_000 },
  reporter: [
    ["json", { outputFile: "results.json" }],
    ["list"],
  ],
  retries: 1,
  workers: 1, // journeys are sequential — same DB, avoid interference
  use: {
    ...devices["Pixel 5"],
    baseURL: process.env.JOURNEY_BASE_URL || "http://localhost:3000",
    video: "retain-on-failure",
    screenshot: "only-on-failure",
    trace: "retain-on-failure",
    ignoreHTTPSErrors: true,
  },
});
