"""IR Migration — convert existing code-generated projects to IR.

For projects generated by the old LLM code-first pipeline, this module
attempts to construct IR from the existing code. Unrecognizable sections
become Custom nodes.

This is best-effort. Old projects keep working either way.
"""

from __future__ import annotations

import json
import logging
import re
from pathlib import Path
from typing import Any

logger = logging.getLogger(__name__)


async def migrate_to_ir(output_dir: str) -> dict[str, Any]:
    """Attempt to convert a code-first project to IR.

    Strategy:
    1. Read the registry (entities, routes, pages) — this is the plan
    2. Convert registry to AppSpec
    3. Generate IR from AppSpec
    4. Save IR alongside existing code (non-destructive)

    Returns:
        Dict with migration status and details.
    """
    from services.registry import load_registry
    from services.ir_adapter import plan_to_app_spec
    from services.ir_compiler import generate_ir_from_spec, save_ir

    result = {
        "success": False,
        "pages_created": 0,
        "entities_found": 0,
        "message": "",
    }

    # Step 1: Read existing registry or plan
    registry = load_registry(output_dir)
    if not registry or not registry.get("entities"):
        # Try to read plan.json
        plan_path = Path(output_dir) / "plan.json"
        if plan_path.exists():
            plan = json.loads(plan_path.read_text(encoding="utf-8"))
        else:
            # Try to scan src/ directory for pages and create a minimal plan
            plan = _scan_source_for_plan(output_dir)
            if not plan:
                result["message"] = "No registry, plan, or source files found. Cannot migrate."
                return result
    else:
        # Convert registry to plan-like structure
        plan = _registry_to_plan(registry, output_dir)

    # Step 2: Convert to AppSpec
    app_name = plan.get("module_name", "Migrated App")
    app_spec = plan_to_app_spec(plan, app_name)
    result["entities_found"] = len(app_spec.get("entities", []))

    if result["entities_found"] == 0:
        result["message"] = "No entities found in registry/plan."
        return result

    # Step 3: Generate IR
    try:
        ir = await generate_ir_from_spec(app_spec)
    except Exception as e:
        result["message"] = f"IR generation failed: {str(e)}"
        return result

    result["pages_created"] = len(ir.get("pages", []))

    # Step 4: Save IR (non-destructive — doesn't overwrite existing code)
    await save_ir(output_dir, ir)

    result["success"] = True
    result["message"] = (
        f"Migration complete: {result['entities_found']} entities, "
        f"{result['pages_created']} IR pages created. "
        f"Existing code is unchanged — IR saved to .ir/ directory."
    )

    logger.info("IR migration: %s", result["message"])
    return result


def _registry_to_plan(registry: dict, output_dir: str) -> dict:
    """Convert a registry dict to a plan-like structure for the adapter."""
    plan: dict[str, Any] = {
        "module_name": "Migrated App",
        "description": "",
        "data_models": [],
        "api_routes": [],
        "pages": [],
        "relations": [],
    }

    # Entities
    for entity_name, entity_data in registry.get("entities", {}).items():
        fields = []
        for field_name, field_info in entity_data.get("fields", {}).items():
            field: dict[str, Any] = {
                "name": field_name,
                "type": field_info.get("type", "String"),
            }
            if field_info.get("primaryKey"):
                field["primaryKey"] = True
            if field_info.get("nullable") is False:
                field["nullable"] = False
            if field_info.get("enum_values"):
                field["type"] = "Enum"
                field["enum_values"] = field_info["enum_values"]
            fields.append(field)

        plan["data_models"].append({
            "name": entity_name,
            "fields": fields,
        })

    # Routes
    for route_key, route_info in registry.get("api_routes", {}).items():
        parts = route_key.split(" ", 1)
        if len(parts) == 2:
            plan["api_routes"].append({
                "method": parts[0],
                "path": parts[1],
                "entity": route_info.get("entity", ""),
            })

    # Pages
    for route, page_info in registry.get("pages", {}).items():
        plan["pages"].append({
            "route": route,
            "name": route.strip("/").replace("/", " ").title(),
            "description": "",
        })

    # Relations
    for rel in registry.get("relations", []):
        plan["relations"].append(rel)

    # Try to get app name from package.json
    pkg_path = Path(output_dir) / "package.json"
    if pkg_path.exists():
        try:
            pkg = json.loads(pkg_path.read_text())
            plan["module_name"] = pkg.get("name", "Migrated App")
        except Exception:
            pass

    return plan


def _scan_source_for_plan(output_dir: str) -> dict | None:
    """Scan source files to build a minimal plan when no registry/plan exists.

    Used for Figma-generated projects that have source code but no registry.
    Looks at page.tsx files to infer entities and routes.
    """
    src_dir = Path(output_dir) / "src"
    if not src_dir.exists():
        return None

    plan: dict[str, Any] = {
        "module_name": "Migrated App",
        "description": "",
        "data_models": [],
        "api_routes": [],
        "pages": [],
        "relations": [],
    }

    # Scan for page.tsx files to discover routes/entities
    page_files = list(src_dir.rglob("page.tsx"))
    if not page_files:
        return None

    seen_entities = set()
    for pf in page_files:
        rel = pf.relative_to(src_dir)
        parts = list(rel.parts)
        # Remove "app" prefix and "page.tsx" suffix
        if parts and parts[0] == "app":
            parts = parts[1:]
        if parts and parts[-1] == "page.tsx":
            parts = parts[:-1]

        route = "/" + "/".join(parts) if parts else "/"

        # Skip auth/api routes and layout groups
        if any(p.startswith("(") or p == "api" for p in parts):
            continue

        page_name = " ".join(parts).title() if parts else "Home"
        plan["pages"].append({
            "route": route,
            "name": page_name,
            "description": "",
        })

        # Infer entity from route (e.g., /tasks → Task, /users → User)
        if parts and not parts[0].startswith("["):
            entity_name = parts[0].rstrip("s").title()
            if entity_name and entity_name not in seen_entities and not entity_name.startswith("["):
                seen_entities.add(entity_name)
                plan["data_models"].append({
                    "name": entity_name,
                    "fields": [
                        {"name": "id", "type": "String", "primaryKey": True},
                        {"name": "name", "type": "String", "nullable": False},
                    ],
                })
                plan["api_routes"].append({"method": "GET", "path": f"/api/{parts[0]}", "entity": entity_name})
                plan["api_routes"].append({"method": "POST", "path": f"/api/{parts[0]}", "entity": entity_name})

    # Scan for API route files for more accurate entity discovery
    api_dir = src_dir / "app" / "api"
    if api_dir.exists():
        for route_file in api_dir.rglob("route.ts"):
            rel = route_file.relative_to(api_dir)
            parts = [p for p in rel.parts if p != "route.ts" and not p.startswith("[")]
            if parts:
                entity_name = parts[0].rstrip("s").title()
                if entity_name not in seen_entities:
                    seen_entities.add(entity_name)
                    plan["data_models"].append({
                        "name": entity_name,
                        "fields": [
                            {"name": "id", "type": "String", "primaryKey": True},
                            {"name": "name", "type": "String", "nullable": False},
                        ],
                    })

    # Try to get app name from package.json
    pkg_path = Path(output_dir) / "package.json"
    if pkg_path.exists():
        try:
            pkg = json.loads(pkg_path.read_text())
            plan["module_name"] = pkg.get("name", "Migrated App")
        except Exception:
            pass

    # Even without data models, if we found pages, return the plan
    if not plan["data_models"] and not plan["pages"]:
        return None

    # If we have pages but no data models, add a dummy entity so the
    # pattern generator has something to work with
    if not plan["data_models"] and plan["pages"]:
        plan["data_models"].append({
            "name": "Item",
            "fields": [
                {"name": "id", "type": "String", "primaryKey": True},
                {"name": "name", "type": "String", "nullable": False},
            ],
        })
        plan["api_routes"].append({"method": "GET", "path": "/api/items", "entity": "Item"})

    return plan
