"""onboarding_tour_pass — Spec E Wave 3 (advanced UX patterns).

When the planner declares ``journey.onboarding`` on the plan, this
deterministic post-gen pass emits a JSON file describing the tour and
adds a ``TourOverlay`` node to the shell so first-run users see the
guided step-through automatically.

Flag-gated on ``FORGE_E_PATTERNS`` — no-op unless the operator opts
in. Additive + idempotent: safe to re-run.

Design notes
------------
* We do NOT modify individual page schemas — the tour is a single
  overlay in the shell that reads its own step list and only opens
  when the user hasn't dismissed it (localStorage-persisted).
* The steps file is written to ``src/config/onboarding-tour.json`` so
  the shell can import it without any codegen. Path is stable across
  regens which is the point.
* When a step declares a ``page`` and the current pathname doesn't
  match, the runtime component skips forward to the next matching
  step — meaning multi-page tours degrade to per-page tours cleanly.
* We also emit a tiny ``useTour()`` bootstrapper helper at
  ``src/lib/useTour.ts`` — the shell template imports it once and
  the TourOverlay picks up the right storage key + step list.
"""
from __future__ import annotations

import glob
import json
import logging
import os
from pathlib import Path
from typing import Any

logger = logging.getLogger(__name__)


def is_enabled() -> bool:
    return os.getenv("FORGE_E_PATTERNS", "0").strip().lower() in {
        "1", "true", "yes", "on",
    }


_USE_TOUR_TS = """\
/**
 * Auto-generated by services.onboarding_tour_pass (Spec E Wave 3).
 * Loads the tour step list + storage key from JSON. The shell wires
 * this into a <TourOverlay />.
 */
import onboarding from \"../config/onboarding-tour.json\";

export type TourStep = {
  target: string;
  title: string;
  body?: string;
  placement?: \"top\" | \"bottom\" | \"left\" | \"right\" | \"auto\";
  page?: string;
};

export function useTour(): { steps: TourStep[]; storageKey: string } {
  const raw = onboarding as { steps: TourStep[]; storageKey?: string };
  return {
    steps: Array.isArray(raw.steps) ? raw.steps : [],
    storageKey: raw.storageKey || \"forge-onboarding-tour\",
  };
}
"""


def _normalize_steps(steps: list[Any]) -> list[dict]:
    out: list[dict] = []
    for s in steps:
        if not isinstance(s, dict):
            continue
        sel = s.get("target_selector") or s.get("target")
        title = s.get("title")
        if not isinstance(sel, str) or not sel.strip():
            continue
        if not isinstance(title, str) or not title.strip():
            continue
        entry: dict[str, Any] = {
            "target": sel.strip(),
            "title": title.strip(),
        }
        if isinstance(s.get("body"), str) and s["body"].strip():
            entry["body"] = s["body"].strip()
        if isinstance(s.get("page"), str) and s["page"].strip():
            entry["page"] = s["page"].strip()
        placement = s.get("placement")
        if placement in ("top", "bottom", "left", "right", "auto"):
            entry["placement"] = placement
        out.append(entry)
    return out


def _load_plan(root: Path) -> dict:
    for rel in ("contracts/plan.json", "src/contracts/plan.json", "plan.json"):
        fp = root / rel
        if not fp.exists():
            continue
        try:
            return json.loads(fp.read_text(encoding="utf-8"))
        except Exception:
            continue
    return {}


def _shell_files(root: Path) -> list[Path]:
    """Best-effort discovery of the shell / root-layout file(s) that
    should carry the TourOverlay mount. We look at the common paths;
    when none exist we skip the injection (the JSON+helper are still
    emitted so a downstream template can pick them up).
    """
    candidates = [
        root / "src" / "app" / "layout.tsx",
        root / "src" / "app" / "layout.jsx",
        root / "src" / "shell" / "AppShell.tsx",
    ]
    return [c for c in candidates if c.exists()]


_IMPORT_LINE = 'import { TourOverlay } from "@tentoroforge/library";\n'
_USE_TOUR_IMPORT = 'import { useTour } from "@/lib/useTour";\n'
_TOUR_TAG_LINE = "        <TourOverlay steps={__tour.steps} storageKey={__tour.storageKey} />\n"


def _inject_into_shell(shell: Path) -> bool:
    """Inject imports + `<TourOverlay />` into a shell/layout file.

    Very conservative: only writes if the file doesn't already mention
    ``TourOverlay``. Otherwise we assume the shell already handles it.
    """
    try:
        src = shell.read_text(encoding="utf-8")
    except Exception:
        return False
    if "TourOverlay" in src:
        return False

    # Add the two imports at the top (after any existing "use client";
    # otherwise at the very top).
    lines = src.splitlines(keepends=True)
    insert_at = 0
    if lines and lines[0].strip().startswith('"use client"'):
        insert_at = 1
    lines.insert(insert_at, _IMPORT_LINE)
    lines.insert(insert_at + 1, _USE_TOUR_IMPORT)

    new_src = "".join(lines)
    # Drop-in near the top of the returned JSX. Rather than deeply
    # parse TSX (fragile), we detect the first `return (` and inject a
    # sibling wrapper. The Overlay is layout-neutral so ordering
    # doesn't matter visually.
    marker = "return ("
    idx = new_src.find(marker)
    if idx == -1:
        return False
    # Insert a preamble that reads the tour just above the return.
    preamble = "  const __tour = useTour();\n  "
    # Only inject preamble once
    if "const __tour = useTour()" not in new_src:
        new_src = new_src[:idx] + preamble + new_src[idx:]
        idx = new_src.find(marker, idx)  # re-locate after the splice

    # Find the first opening JSX tag after `return (` and insert the
    # TourOverlay right after it.
    open_paren = new_src.find("(", idx) + 1
    lt = new_src.find("<", open_paren)
    if lt == -1:
        return False
    gt = new_src.find(">", lt)
    if gt == -1:
        return False
    insert_pos = gt + 1
    new_src = new_src[:insert_pos] + "\n" + _TOUR_TAG_LINE + new_src[insert_pos:]

    shell.write_text(new_src, encoding="utf-8")
    return True


def _copy_wildcard_plan_if_missing(root: Path) -> dict:
    """When no plan.json is on disk we can still emit an empty tour
    (a valid file that opts nothing in) so the JSON path is stable.
    Callers rely on that stability to avoid conditional imports in
    the shell.
    """
    return _load_plan(root)


def run(output_dir: str) -> dict[str, Any]:
    """Emit onboarding-tour.json + useTour.ts + inject <TourOverlay/>."""
    report: dict[str, Any] = {
        "enabled": is_enabled(),
        "steps": 0,
        "config_written": False,
        "helper_written": False,
        "shells_patched": [],
    }
    if not is_enabled():
        return report

    root = Path(output_dir)
    if not root.exists():
        return report

    plan = _copy_wildcard_plan_if_missing(root)
    journey = plan.get("journey") if isinstance(plan, dict) else None
    onb = journey.get("onboarding") if isinstance(journey, dict) else None
    raw_steps = onb.get("steps") if isinstance(onb, dict) else None

    steps: list[dict] = []
    if isinstance(raw_steps, list):
        steps = _normalize_steps(raw_steps)
    if not steps:
        return report  # nothing declared — pass no-ops

    report["steps"] = len(steps)

    # 1. Emit the JSON step-list under src/config/
    cfg_dir = root / "src" / "config"
    cfg_dir.mkdir(parents=True, exist_ok=True)
    cfg_file = cfg_dir / "onboarding-tour.json"
    cfg_file.write_text(json.dumps({
        "storageKey": "forge-onboarding-tour",
        "steps": steps,
    }, indent=2), encoding="utf-8")
    report["config_written"] = True

    # 2. Emit the useTour helper.
    lib_dir = root / "src" / "lib"
    lib_dir.mkdir(parents=True, exist_ok=True)
    helper_file = lib_dir / "useTour.ts"
    if not helper_file.exists() or helper_file.read_text(encoding="utf-8") != _USE_TOUR_TS:
        helper_file.write_text(_USE_TOUR_TS, encoding="utf-8")
    report["helper_written"] = True

    # 3. Inject <TourOverlay /> into the shell / root layout(s).
    for shell in _shell_files(root):
        try:
            if _inject_into_shell(shell):
                report["shells_patched"].append(str(shell.relative_to(root)))
        except Exception as exc:  # noqa: BLE001
            logger.warning("onboarding_tour_pass: shell inject failed on %s: %s", shell, exc)

    logger.info(
        "onboarding_tour_pass: steps=%d config=%s shells_patched=%s",
        report["steps"], report["config_written"], report["shells_patched"],
    )
    return report


# Convenience for tests / callers that want to enumerate schemas that
# will benefit — parity with the other passes' surface area.
def enumerate_onboarding_steps(output_dir: str) -> list[dict]:
    plan = _load_plan(Path(output_dir))
    if not isinstance(plan, dict):
        return []
    j = plan.get("journey")
    if not isinstance(j, dict):
        return []
    o = j.get("onboarding")
    if not isinstance(o, dict):
        return []
    steps = o.get("steps")
    return _normalize_steps(steps) if isinstance(steps, list) else []


# Silence unused-import warnings when the module is imported for its
# type surface.
_ = glob
