/**
 * GET /api/tasks/[id] — return a single workflow task by id.
 *
 * The task detail page (src/app/tasks/[id]/page.tsx) fetches this to
 * render the task's process_variables and form_binding before showing
 * the decision form. Ships alongside the /api/tasks list route
 * (already generated by runtime_injector).
 *
 * Auth-gated. A user may fetch a task if:
 *   - it is assigned to their id, OR
 *   - it is assigned to their role, OR
 *   - it is unassigned (assignee_id AND assignee_role both null).
 *
 * Returns 404 for anything else so a stranger can't enumerate task ids.
 */
import { NextResponse } from "next/server";
import { auth } from "@/auth";
import { db } from "@/db";
import { sql } from "drizzle-orm";

export async function GET(
  _request: Request,
  { params }: { params: Promise<{ id: string }> },
) {
  const session = await auth();
  if (!session?.user) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }

  const { id } = await params;
  const userId = (session.user as any).id || "";
  const userRole = (session.user as any).role || "";

  try {
    const res: any = await db.execute(sql`
      SELECT id, workflow_id, workflow_instance_id, node_id, node_label,
             task_type, status, assignee_id, assignee_role,
             entity_type, entity_id, process_variables, form_binding,
             due_at, created_at
      FROM workflow_tasks
      WHERE id = ${id}::uuid
        AND (
          assignee_id = ${userId}::text
          OR assignee_role = ${userRole}
          OR (assignee_id IS NULL AND assignee_role IS NULL)
        )
      LIMIT 1
    `);
    const row = (res.rows ?? res)?.[0];
    if (!row) {
      return NextResponse.json({ error: "Not found" }, { status: 404 });
    }
    return NextResponse.json(row);
  } catch {
    // Table may not exist yet (fresh app) — treat as 404 rather than 500.
    return NextResponse.json({ error: "Not found" }, { status: 404 });
  }
}
