/**
 * Workflow Event Trigger Route
 *
 * POST /api/workflows/event/[event]
 *
 * Triggers all workflows whose trigger.type === "api_event" and
 * trigger.event matches the [event] path parameter.
 *
 * Auto-generated by Tentoro Forge runtime injector.
 */

import { NextResponse } from "next/server";
import { triggerWorkflowEvent } from "@/lib/workflows";
import { initializeRuntime } from "@/lib/runtime-loader";
import { auth } from "@/auth";

export async function POST(
  request: Request,
  { params }: { params: Promise<{ event: string }> },
) {
  await initializeRuntime();

  try {
    const { event } = await params;
    const body = await request.json().catch(() => ({}));
    const input = body.input || body || {};
    // Acting user from the SERVER session (workflow runtime defaults owner FKs
    // from ctx.user.id — see the [id]/execute route).
    const session = await auth();
    const su = session?.user as { id?: string; role?: string; email?: string | null } | undefined;
    const user = su?.id ? { id: su.id, role: su.role, email: su.email ?? undefined } : body.user;

    const results = await triggerWorkflowEvent(event, input, user);

    return NextResponse.json({ event, results });
  } catch (error) {
    return NextResponse.json(
      { error: error instanceof Error ? error.message : String(error) },
      { status: 500 },
    );
  }
}
