// Schema registry — maps ROUTE to a dynamic import that resolves the raw JSON.
// This file is REGENERATED by the schema pipeline (schema_pipeline.py writes an
// "Auto-generated" version keyed on real routes). The stub below is only used
// on foundation-only builds where the pipeline hasn't run yet.

import { loadSchema } from "./load";

export const schemas: Record<string, () => Promise<unknown>> = {};

export async function getSchema(name: keyof typeof schemas): Promise<ReturnType<typeof loadSchema>> {
  const loader = schemas[name as string];
  if (!loader) throw new Error(`unknown schema '${String(name)}'`);
  const raw = await loader();
  return loadSchema(name as string, (raw as any).default ?? raw);
}
