"""Emit Playwright test files into a generated app.

Three files land in `<app>/journeys/`:

  journeys.json         — the JourneySpec, read at test time
  playwright.config.ts  — projects=chromium mobile, retries=1, video=on-failure
  driver.spec.ts        — DATA-DRIVEN driver (one test per journey, dispatches
                          each step off `step.kind`)

The driver is DOMAIN-AGNOSTIC. It never mentions "scan" or "product" or
"retailer". Every app gets the same driver; only journeys.json differs.
That's what makes this work for any domain.
"""
from __future__ import annotations

import json
from pathlib import Path

from .spec import JourneySpec


PLAYWRIGHT_CONFIG_TS = """\
// AUTO-GENERATED by backend/services/journey_verifier/emitter.py
// Do not hand-edit. Regenerated on every pipeline pass.

import { defineConfig, devices } from "@playwright/test";

export default defineConfig({
  testDir: __dirname,
  // driver = declared journeys; sweep = whole-route empty/error/screenshot
  // pass (emitted separately by sweep.py — a missing sweep.spec.ts is fine,
  // testMatch entries are patterns, not requirements).
  testMatch: ["driver.spec.ts", "sweep.spec.ts"],
  timeout: 120_000,
  expect: { timeout: 10_000 },
  reporter: [
    ["json", { outputFile: "results.json" }],
    ["list"],
  ],
  retries: 1,
  workers: 1, // journeys are sequential — same DB, avoid interference
  use: {
    ...devices["Pixel 5"],
    baseURL: process.env.JOURNEY_BASE_URL || "http://localhost:3000",
    video: "retain-on-failure",
    screenshot: "only-on-failure",
    trace: "retain-on-failure",
    ignoreHTTPSErrors: true,
  },
});
"""


DRIVER_SPEC_TS = r"""// AUTO-GENERATED by backend/services/journey_verifier/emitter.py
// Data-driven Playwright journey runner. Reads journeys.json and executes
// each journey step-by-step, dispatching on step.kind. Works for ANY app —
// the vocabulary of steps is fixed; the meaning is app-specific.

import { test, expect, Page } from "@playwright/test";
import fs from "node:fs";
import path from "node:path";
import { Pool } from "pg";

type Locator = {
  journey_slug?: string;
  role?: string;
  label?: string;
  text?: string;
  css?: string;
};

type EntityFilter = {
  entity: string;
  where: Record<string, string>;
  min_count?: number;
  equals?: Record<string, unknown>;
};

type WorkflowFilter = {
  workflow_id: string;
  target_status: "completed" | "failed" | "terminal";
  timeout_ms: number;
};

type Step = {
  kind: string;
  name?: string;
  route?: string;
  email?: string;
  password?: string;
  locator?: Locator;
  value?: string | number | boolean;
  fixture?: string;
  entity_filter?: EntityFilter;
  workflow_filter?: WorkflowFilter;
  timeout_ms: number;
};

type Journey = {
  slug: string;
  name: string;
  actor: string;
  tags: string[];
  steps: Step[];
};

type JourneySpec = {
  app_slug: string;
  archetype: string;
  base_url: string;
  seed_users: Array<{ email: string; password: string; role?: string }>;
  fixtures: Record<string, string>;
  journeys: Journey[];
};

const specPath = path.join(__dirname, "journeys.json");
const spec: JourneySpec = JSON.parse(fs.readFileSync(specPath, "utf8"));

// Direct DB connection for entity/workflow assertions. The app's own /api
// routes are auth-gated and would introduce circular concerns — asserting
// SQL directly is faster and less fragile for verification.
const dbUrl =
  process.env.JOURNEY_DB_URL ||
  process.env.DATABASE_URL ||
  "postgresql://postgres:postgres@localhost:5444/app";
const db = new Pool({ connectionString: dbUrl });

// ── file upload polling ───────────────────────────────────────────────────
// Used by `upload` to wait for the async /api/files/upload POST to land a
// row in forge_files before we hand control back — otherwise the next step
// (typically a Form submit) races the upload and dispatches with an empty
// hidden input, which is exactly the null-imageUrl bug caught in prod.
async function countFiles(): Promise<number> {
  try {
    const { rows } = await db.query("SELECT COUNT(*)::int AS n FROM forge_files");
    return rows[0]?.n ?? 0;
  } catch { return 0; }
}

// ── locator resolution ────────────────────────────────────────────────────
// Priority: data-journey → role+label → label as text → CSS. Emitters SHOULD
// stamp `data-journey` on plan-referenced controls; the fallbacks keep the
// driver useful on apps that haven't opted into the attribute yet.
function resolveLocator(page: Page, loc: Locator) {
  if (loc.journey_slug) return page.locator(`[data-journey="${loc.journey_slug}"]`);
  if (loc.role && loc.label) {
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    return page.getByRole(loc.role as any, { name: loc.label });
  }
  if (loc.text) return page.getByText(loc.text, { exact: false });
  if (loc.css) return page.locator(loc.css);
  throw new Error("Locator has no strategy: " + JSON.stringify(loc));
}

// ── entity polling ────────────────────────────────────────────────────────
async function pollEntity(f: EntityFilter, timeoutMs: number) {
  const deadline = Date.now() + timeoutMs;
  const table = f.entity;
  const whereClauses: string[] = [];
  const params: unknown[] = [];
  let i = 1;
  for (const [col, val] of Object.entries(f.where || {})) {
    whereClauses.push(`${col} = $${i++}`);
    params.push(val);
  }
  const sql =
    `SELECT COUNT(*)::int AS n FROM ${table}` +
    (whereClauses.length ? ` WHERE ${whereClauses.join(" AND ")}` : "");
  const minCount = f.min_count ?? 1;
  while (Date.now() < deadline) {
    const { rows } = await db.query(sql, params);
    if ((rows[0]?.n || 0) >= minCount) return rows[0].n;
    await new Promise((r) => setTimeout(r, 500));
  }
  throw new Error(
    `wait_for_entity timed out: ${table} matching ${JSON.stringify(f.where)} ` +
      `(needed ≥${minCount})`,
  );
}

// ── workflow polling ──────────────────────────────────────────────────────
async function pollWorkflow(f: WorkflowFilter) {
  const deadline = Date.now() + (f.timeout_ms || 90_000);
  while (Date.now() < deadline) {
    const { rows } = await db.query(
      `SELECT status FROM workflow_execution_log
         WHERE workflow_id = $1 AND node_id = $2
         ORDER BY created_at DESC LIMIT 1`,
      [f.workflow_id, "end"],
    );
    if (rows.length) {
      const s: string = rows[0].status;
      if (f.target_status === "terminal" && ["completed", "failed"].includes(s)) return s;
      if (f.target_status === s) return s;
    }
    // Also treat a mark_completed / mark_failed node as terminal if there's
    // no explicit `end` — many workflows don't have one.
    const { rows: term } = await db.query(
      `SELECT status FROM workflow_execution_log
         WHERE workflow_id = $1 AND node_id LIKE 'mark_%'
         ORDER BY created_at DESC LIMIT 1`,
      [f.workflow_id],
    );
    if (term.length) {
      const s: string = term[0].status;
      if (f.target_status === "terminal" && ["completed", "failed"].includes(s)) return s;
      if (f.target_status === s) return s;
    }
    await new Promise((r) => setTimeout(r, 750));
  }
  throw new Error(
    `wait_for_workflow timed out: ${f.workflow_id} not ${f.target_status}`,
  );
}

// ── step dispatcher ───────────────────────────────────────────────────────
async function runStep(page: Page, step: Step, ctx: { errors: string[] }) {
  const label = step.name || step.kind;
  await test.step(label, async () => {
    switch (step.kind) {
      case "visit": {
        if (!step.route) throw new Error("visit needs route");
        await page.goto(step.route);
        break;
      }
      case "login_as": {
        // Robust login: try (a) semantic labels, (b) input types, (c) name
        // attrs — the login form's exact accessible pattern varies per
        // template. Always ends by waiting for the URL to leave /login.
        if (!step.email || !step.password) throw new Error("login_as needs email+password");
        await page.goto("/login");
        await page.waitForLoadState("domcontentloaded");
        const emailInput = page.locator([
          'input[type="email"]',
          'input[name="email"]',
          'input[autocomplete="email"]',
          'input[placeholder*="mail" i]',
        ].join(", ")).first();
        const passwordInput = page.locator([
          'input[type="password"]',
          'input[name="password"]',
          'input[autocomplete~="password"]',
        ].join(", ")).first();
        await emailInput.waitFor({ state: "visible", timeout: 10_000 });
        await emailInput.fill(step.email);
        await passwordInput.fill(step.password);
        const submitButton = page.locator([
          'button[type="submit"]',
          'button:has-text("Sign in")',
          'button:has-text("Sign In")',
          'button:has-text("Log in")',
          'button:has-text("Login")',
        ].join(", ")).first();
        await submitButton.click();
        await page.waitForURL((url) => !url.pathname.startsWith("/login"), {
          timeout: step.timeout_ms,
        });
        break;
      }
      case "logout": {
        await page.goto("/api/auth/signout");
        break;
      }
      case "fill": {
        if (!step.locator || step.value === undefined) throw new Error("fill needs locator+value");
        await resolveLocator(page, step.locator).fill(String(step.value));
        break;
      }
      case "upload": {
        if (!step.locator || !step.fixture) throw new Error("upload needs locator+fixture");
        const fixturePath = spec.fixtures[step.fixture];
        if (!fixturePath) throw new Error(`unknown fixture: ${step.fixture}`);
        const abs = path.isAbsolute(fixturePath)
          ? fixturePath
          : path.join(__dirname, fixturePath);
        const fileInput = page.locator('input[type="file"]').first();
        const before = await countFiles();
        await fileInput.setInputFiles(abs);
        // The FileUpload component uploads asynchronously and only then
        // sets its hidden input value. A test that clicks Submit right after
        // setInputFiles races that async POST — this is the same failure
        // a fast human user hits. Wait for the file to land in forge_files
        // and for the hidden input's `value` attribute to be non-empty
        // before returning control to the next step.
        const deadline = Date.now() + step.timeout_ms;
        while (Date.now() < deadline) {
          if ((await countFiles()) > before) {
            const hiddenValue = await page
              .locator('input[type="hidden"][name]:not([value=""])')
              .first()
              .getAttribute("value")
              .catch(() => null);
            if (hiddenValue) return;
          }
          await new Promise((r) => setTimeout(r, 400));
        }
        throw new Error(`upload never completed within ${step.timeout_ms}ms`);
      }
      case "click": {
        if (!step.locator) throw new Error("click needs locator");
        await resolveLocator(page, step.locator).click({ timeout: step.timeout_ms });
        break;
      }
      case "select": {
        if (!step.locator || step.value === undefined) throw new Error("select needs locator+value");
        await resolveLocator(page, step.locator).selectOption(String(step.value));
        break;
      }
      case "wait_for_route": {
        if (!step.route) throw new Error("wait_for_route needs route");
        await page.waitForURL(new RegExp(step.route.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")), {
          timeout: step.timeout_ms,
        });
        break;
      }
      case "wait_for_element": {
        if (!step.locator) throw new Error("wait_for_element needs locator");
        await resolveLocator(page, step.locator).waitFor({
          state: "visible",
          timeout: step.timeout_ms,
        });
        break;
      }
      case "wait_for_entity": {
        if (!step.entity_filter) throw new Error("wait_for_entity needs entity_filter");
        await pollEntity(step.entity_filter, step.timeout_ms);
        break;
      }
      case "wait_for_workflow": {
        if (!step.workflow_filter) throw new Error("wait_for_workflow needs workflow_filter");
        await pollWorkflow(step.workflow_filter);
        break;
      }
      case "assert_element": {
        if (!step.locator) throw new Error("assert_element needs locator");
        const loc = resolveLocator(page, step.locator);
        await expect(loc).toBeVisible({ timeout: step.timeout_ms });
        if (step.value) await expect(loc).toContainText(String(step.value));
        break;
      }
      case "assert_route": {
        if (!step.route) throw new Error("assert_route needs route");
        expect(page.url()).toContain(step.route);
        break;
      }
      case "assert_entity": {
        if (!step.entity_filter) throw new Error("assert_entity needs entity_filter");
        const n = await pollEntity(step.entity_filter, step.timeout_ms);
        expect(n).toBeGreaterThanOrEqual(step.entity_filter.min_count ?? 1);
        break;
      }
      case "assert_no_console_errors": {
        expect(ctx.errors, ctx.errors.join("\n")).toHaveLength(0);
        break;
      }
      default:
        throw new Error(`Unknown step kind: ${step.kind}`);
    }
  });
}

// ── one test per journey ──────────────────────────────────────────────────
for (const journey of spec.journeys) {
  test(`${journey.slug} · ${journey.name}`, async ({ page }) => {
    const errors: string[] = [];
    page.on("pageerror", (e) => errors.push(`pageerror: ${e.message}`));
    page.on("console", (msg) => {
      if (msg.type() === "error") errors.push(`console.error: ${msg.text()}`);
    });

    for (const step of journey.steps) {
      await runStep(page, step, { errors });
    }
  });
}

test.afterAll(async () => {
  await db.end();
});
"""


def emit(spec: JourneySpec, output_dir: Path | str) -> Path:
    """Emit the three journey files into `<output_dir>/journeys/`.

    Returns the journeys directory. Idempotent — safe to call every
    generation. Overwrites journeys.json, driver.spec.ts, and the config;
    doesn't touch fixtures the caller (or test authors) placed there.
    """
    output_dir = Path(output_dir)
    journeys_dir = output_dir / "journeys"
    journeys_dir.mkdir(parents=True, exist_ok=True)

    (journeys_dir / "journeys.json").write_text(
        json.dumps(spec.to_dict(), indent=2, sort_keys=False)
    )
    (journeys_dir / "playwright.config.ts").write_text(PLAYWRIGHT_CONFIG_TS)
    (journeys_dir / "driver.spec.ts").write_text(DRIVER_SPEC_TS)

    return journeys_dir
