"""Page sweep — visit every registered route, prove nothing renders
empty, and capture a screenshot per page (SMOKE-2 + the capture half of
the G1 visual-QA loop).

The journeys walk the *declared* flows; this sweep walks the whole
route surface. Per route it records what the static binding smoke can't
see — the app as actually rendered against the actually-seeded DB:

  - ``emptyMarkers``  — count of ``[data-empty="true"]`` elements
    (library components stamp this when a binding resolved to nothing),
  - ``pageErrors``    — uncaught page/console errors during render,
  - ``screenshot``    — ``journeys/artifacts/sweep/<slug>.png``, the
    input for the visual-QA critic and the visual-regression baseline.

Param routes (``/documents/[id]``) are resolved against the live DB
(``SELECT id FROM <table> LIMIT 1`` — same Pool the journey driver
uses); a param route with no row is itself recorded as ``no_row``.

Emission is deterministic Python → ``sweep.json`` + ``sweep.spec.ts``
in the app's ``journeys/`` dir; the existing harness runs it in the
same Playwright invocation as the journeys (config testMatch includes
it). Results land in ``journeys/sweep-results.json``.
"""
from __future__ import annotations

import json
import logging
from pathlib import Path

from services.binding_validator import _read_schema_tables, _SlugResolver
from services.delivery_gate import _load_registry_routes

logger = logging.getLogger(__name__)

# Routes the sweep never visits: auth screens redirect the sweep's own
# session, and api/asset paths aren't pages.
_SKIP_PREFIXES = ("/login", "/signup", "/api", "/_next", "/shell")


SWEEP_SPEC_TS = r"""// AUTO-GENERATED by backend/services/journey_verifier/sweep.py
// Route sweep: login once, visit every registered route, count
// [data-empty] markers, collect page errors, screenshot each page.
// Results: sweep-results.json (read by the SV harness).

import { test, Page } from "@playwright/test";
import fs from "node:fs";
import path from "node:path";
import { Pool } from "pg";

type SweepRoute = { route: string; table?: string };
type SweepManifest = { routes: SweepRoute[] };

const manifest: SweepManifest = JSON.parse(
  fs.readFileSync(path.join(__dirname, "sweep.json"), "utf8"),
);
const journeySpec = JSON.parse(
  fs.readFileSync(path.join(__dirname, "journeys.json"), "utf8"),
);

const dbUrl =
  process.env.JOURNEY_DB_URL ||
  process.env.DATABASE_URL ||
  "postgresql://postgres:postgres@localhost:5444/app";
const db = new Pool({ connectionString: dbUrl });

const artifactsDir = path.join(__dirname, "artifacts", "sweep");
fs.mkdirSync(artifactsDir, { recursive: true });

type SweepResult = {
  route: string;
  resolved: string;
  status: "ok" | "no_row" | "nav_failed";
  emptyMarkers: number;
  pageErrors: string[];
  screenshot: string | null;
};
const results: SweepResult[] = [];

async function login(page: Page): Promise<void> {
  const user = (journeySpec.seed_users || [])[0];
  if (!user) return; // unauthenticated app — sweep straight through
  await page.goto("/login");
  const email = page
    .getByLabel(/email/i)
    .or(page.locator('input[type="email"]'))
    .or(page.locator('input[name*="email" i]'))
    .first();
  await email.fill(user.email);
  const pw = page
    .getByLabel(/password/i)
    .or(page.locator('input[type="password"]'))
    .first();
  await pw.fill(user.password);
  await page
    .getByRole("button", { name: /sign in|log ?in|submit/i })
    .first()
    .click();
  await page.waitForURL((url) => !url.pathname.startsWith("/login"), {
    timeout: 15_000,
  });
}

async function resolveRoute(r: SweepRoute): Promise<string | null> {
  const m = r.route.match(/\[([^\]]+)\]/);
  if (!m) return r.route;
  if (!r.table) return null;
  try {
    const { rows } = await db.query(
      `SELECT id FROM "${r.table}" LIMIT 1`,
    );
    if (!rows.length) return null;
    return r.route.replace(/\[[^\]]+\]/, String(rows[0].id));
  } catch {
    return null;
  }
}

test("route sweep", async ({ page }) => {
  test.setTimeout(300_000);
  const errors: string[] = [];
  page.on("pageerror", (e) => errors.push(`pageerror: ${e.message}`));
  page.on("console", (msg) => {
    if (msg.type() === "error") errors.push(`console.error: ${msg.text()}`);
  });

  await login(page);

  for (const r of manifest.routes) {
    const before = errors.length;
    const resolved = await resolveRoute(r);
    if (resolved === null) {
      results.push({
        route: r.route, resolved: "", status: "no_row",
        emptyMarkers: 0, pageErrors: [], screenshot: null,
      });
      continue;
    }
    const slug =
      resolved === "/" ? "index" : resolved.replace(/^\//, "").replace(/\//g, "_");
    const shot = path.join(artifactsDir, `${slug}.png`);
    let status: SweepResult["status"] = "ok";
    let emptyMarkers = 0;
    try {
      await page.goto(resolved, { waitUntil: "load", timeout: 30_000 });
      // Give client-side data fetches a beat to land; networkidle is
      // flaky under HMR/polling, so cap it and move on.
      await page
        .waitForLoadState("networkidle", { timeout: 8_000 })
        .catch(() => {});
      emptyMarkers = await page.locator('[data-empty="true"]').count();
      await page.screenshot({ path: shot, fullPage: true });
    } catch {
      status = "nav_failed";
    }
    results.push({
      route: r.route,
      resolved,
      status,
      emptyMarkers,
      pageErrors: errors.slice(before),
      screenshot: status === "ok" ? shot : null,
    });
  }
});

test.afterAll(async () => {
  fs.writeFileSync(
    path.join(__dirname, "sweep-results.json"),
    JSON.stringify({ results }, null, 2),
  );
  await db.end();
});
"""


def build_sweep_manifest(output_dir: str | Path) -> dict:
    """Concrete + param routes from the registry; param routes carry the
    backing table (resolved from the first path segment) so the spec can
    fetch a real id."""
    root = Path(output_dir)
    resolver = _SlugResolver(_read_schema_tables(str(root)))
    routes: list[dict] = []
    for route in sorted(_load_registry_routes(root)):
        # Registry routes come back normalized to {param} braces.
        route = route.replace("{", "[").replace("}", "]")
        if route.startswith(_SKIP_PREFIXES):
            continue
        entry: dict = {"route": route}
        if "[" in route:
            seg = route.lstrip("/").split("/", 1)[0]
            table = resolver.resolve(seg)
            if table is None:
                continue  # can't resolve a row source — skip, don't guess
            entry["table"] = table
        routes.append(entry)
    return {"routes": routes}


def emit_sweep(output_dir: str | Path) -> Path | None:
    """Write sweep.json + sweep.spec.ts into <app>/journeys/. Idempotent;
    returns the journeys dir, or None when there are no routes to sweep."""
    root = Path(output_dir)
    manifest = build_sweep_manifest(root)
    if not manifest["routes"]:
        return None
    journeys_dir = root / "journeys"
    journeys_dir.mkdir(parents=True, exist_ok=True)
    (journeys_dir / "sweep.json").write_text(
        json.dumps(manifest, indent=2), encoding="utf-8")
    (journeys_dir / "sweep.spec.ts").write_text(SWEEP_SPEC_TS, encoding="utf-8")
    return journeys_dir


def read_sweep_results(output_dir: str | Path) -> dict | None:
    """Parsed sweep-results.json plus a derived summary, or None if the
    sweep didn't run."""
    path = Path(output_dir) / "journeys" / "sweep-results.json"
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
    except Exception:  # noqa: BLE001
        return None
    results = data.get("results") or []
    empty = [r for r in results
             if isinstance(r, dict) and (r.get("emptyMarkers") or 0) > 0]
    failed = [r for r in results
              if isinstance(r, dict) and r.get("status") == "nav_failed"]
    return {
        "results": results,
        "summary": {
            "routes": len(results),
            "with_empty_markers": len(empty),
            "nav_failed": len(failed),
        },
    }


__all__ = ["build_sweep_manifest", "emit_sweep", "read_sweep_results",
           "SWEEP_SPEC_TS"]
