// FEEL-lite cross-engine conformance — TypeScript side.
//
// The condition→FEEL compiler runs here in the browser, but the rules it produces
// evaluate SERVER-SIDE in Python (backend/runtime/feel_lite). If the two engines
// disagree, a condition that reads true in the editor playground reads false in the
// shipped app. This test asserts the TS engine (@/lib/feel-lite) produces the SAME
// result as the Python engine for a shared fixture set whose `expected` values were
// generated by the Python engine (backend/tests/fixtures/feel_conformance.json).
// The Python half (backend/tests/test_feel_conformance.py) asserts the same fixtures.
// Both green ⇒ the engines agree.

import { describe, it, expect } from "vitest";
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";
import { evaluateExpression } from "@/lib/feel-lite";

const here = dirname(fileURLToPath(import.meta.url));
const fixturesPath = resolve(
  here,
  "../../../backend/tests/fixtures/feel_conformance.json",
);

type Case = {
  expr: string;
  data: Record<string, unknown>;
  expected?: unknown;
  error?: string;
};

const cases: Case[] = JSON.parse(readFileSync(fixturesPath, "utf8"));

describe("FEEL-lite conformance: TS engine agrees with Python", () => {
  it("has a substantial shared fixture set", () => {
    expect(cases.length).toBeGreaterThanOrEqual(30);
  });

  for (const c of cases) {
    const label = `${c.expr} | ${JSON.stringify(c.data)}`;
    it(label, () => {
      if (c.error) {
        // Python raised — TS should also not return a clean boolean for this input.
        expect(() => evaluateExpression(c.expr, c.data as never)).toThrow();
        return;
      }
      const got = evaluateExpression(c.expr, c.data as never);
      expect(got).toEqual(c.expected);
    });
  }
});
