"use client";

/**
 * WorkflowTriggerButton — reusable button that triggers a workflow.
 *
 * Usage:
 * ```tsx
 * <WorkflowTriggerButton
 *   workflowId="SurveyPublished"
 *   input={{ surveyId: survey.id }}
 *   label="Publish Survey"
 *   onSuccess={(result) => router.refresh()}
 * />
 * ```
 *
 * Auto-generated by Tentoro Forge runtime injector.
 */

import { useState } from "react";

interface WorkflowTriggerButtonProps {
  workflowId: string;
  input?: Record<string, unknown>;
  label: string;
  className?: string;
  onSuccess?: (result: any) => void;
  onError?: (error: string) => void;
}

export function WorkflowTriggerButton({
  workflowId,
  input = {},
  label,
  className,
  onSuccess,
  onError,
}: WorkflowTriggerButtonProps) {
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState("");

  const handleClick = async () => {
    setLoading(true);
    setError("");
    try {
      const res = await fetch(`/api/workflows/${workflowId}/execute`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ input }),
      });
      const result = await res.json();

      if (!res.ok || result.error) {
        const msg = result.error || "Workflow failed";
        setError(msg);
        onError?.(msg);
      } else {
        onSuccess?.(result);
      }
    } catch (err) {
      const msg = err instanceof Error ? err.message : String(err);
      setError(msg);
      onError?.(msg);
    } finally {
      setLoading(false);
    }
  };

  return (
    <>
      <button
        type="button"
        onClick={handleClick}
        disabled={loading}
        className={
          className ||
          "inline-flex items-center justify-center rounded-md bg-primary text-primary-foreground h-10 px-4 py-2 text-sm font-medium disabled:opacity-50"
        }
      >
        {loading ? "Running..." : label}
      </button>
      {error && (
        <p className="text-sm text-destructive mt-1">{error}</p>
      )}
    </>
  );
}
