import contracts from "@forge/registry/dist/component-contracts.json";

/**
 * Which props a component cannot render without.
 *
 * WHY this is derived rather than declared: `PropDescriptor` has no `required`
 * field, and the panel gave the user no warning at all — `FilterBar.chips` and
 * `MultiSelect.options` are `z.array(...)` with no default in the component
 * contract, so leaving them empty produces a node that renders blank and a user
 * who has no idea which prop they missed (docs/editor-audit Phase 7).
 *
 * The one existing source of truth is the contract snapshot the registry build
 * extracts from the components' own Zod schemas
 * (packages/registry/scripts/extract-contracts.ts → dist/component-contracts.json),
 * where an optional prop carries `optional: true` and a required one carries
 * nothing. Reading that file keeps the panel honest for all 158 components and
 * for whatever the registry adds next, instead of an allowlist that goes stale
 * the moment someone writes a new component.
 *
 * LIMITATIONS, so nobody mistakes this for more than it is:
 *  - 10 structural components (Stack, Grid, GridCell, Repeat, …) are in the
 *    registry but not in the contract snapshot; they simply report nothing.
 *  - The snapshot is a BUILD ARTEFACT. It is regenerated by the registry build,
 *    so it can lag the sources by one build — it is advisory UI, never a gate.
 */
type ContractProp = { optional?: boolean };
const CONTRACTS = contracts as unknown as Record<string, Record<string, ContractProp>>;

export function isRequiredProp(componentName: string, propName: string): boolean {
  const prop = CONTRACTS[componentName]?.[propName];
  return prop !== undefined && prop.optional !== true;
}
