"""add relevant_departments to app_templates

Revision ID: 1dbaa6f922f4
Revises: e24244544c86
Create Date: 2026-02-28 23:16:12.830470
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1dbaa6f922f4'
down_revision: Union[str, None] = 'e24244544c86'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('app_templates', sa.Column('relevant_departments', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('app_templates', 'relevant_departments')
    # ### end Alembic commands ###
