"""add project conversation agent_job version tables

Revision ID: d12dc29cafa1
Revises: 2cd38d3a50ff
Create Date: 2026-02-28 22:49:47.004232
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd12dc29cafa1'
down_revision: Union[str, None] = '2cd38d3a50ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('short_id', sa.String(length=16), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'generating', 'ready', 'error', 'archived', name='project_status'), nullable=False),
    sa.Column('output_dir', sa.String(length=500), nullable=True),
    sa.Column('preview_port', sa.Integer(), nullable=True),
    sa.Column('db_port', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_id'], ['platform_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('short_id')
    )
    op.create_index('ix_project_org', 'projects', ['org_id'], unique=False)
    op.create_index('ix_project_owner', 'projects', ['owner_id'], unique=False)
    op.create_index('ix_project_short_id', 'projects', ['short_id'], unique=False)
    op.create_table('agent_jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('agent_type', sa.Enum('code_generator', 'validator', 'indexer', 'refinement', name='agent_type'), nullable=False),
    sa.Column('status', sa.Enum('pending', 'running', 'completed', 'failed', name='agent_job_status'), nullable=False),
    sa.Column('instruction', sa.Text(), nullable=True),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_job_project', 'agent_jobs', ['project_id'], unique=False)
    op.create_table('conversations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('user', 'assistant', 'system', name='message_role'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('message_type', sa.Enum('chat', 'plan', 'generation', 'error', name='message_type'), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_conv_created', 'conversations', ['created_at'], unique=False)
    op.create_index('ix_conv_project', 'conversations', ['project_id'], unique=False)
    op.create_table('modules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('module_type', sa.String(length=50), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_module_project', 'modules', ['project_id'], unique=False)
    op.create_table('module_dependencies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('module_id', sa.UUID(), nullable=False),
    sa.Column('depends_on_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['depends_on_id'], ['modules.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['module_id'], ['modules.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('commit_hash', sa.String(length=40), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('agent_job_id', sa.UUID(), nullable=True),
    sa.Column('files_changed', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_job_id'], ['agent_jobs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_version_project', 'versions', ['project_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_version_project', table_name='versions')
    op.drop_table('versions')
    op.drop_table('module_dependencies')
    op.drop_index('ix_module_project', table_name='modules')
    op.drop_table('modules')
    op.drop_index('ix_conv_project', table_name='conversations')
    op.drop_index('ix_conv_created', table_name='conversations')
    op.drop_table('conversations')
    op.drop_index('ix_job_project', table_name='agent_jobs')
    op.drop_table('agent_jobs')
    op.drop_index('ix_project_short_id', table_name='projects')
    op.drop_index('ix_project_owner', table_name='projects')
    op.drop_index('ix_project_org', table_name='projects')
    op.drop_table('projects')
    # ### end Alembic commands ###
