// AUTO-GENERATED by services/schema_builder.py — do not hand-edit.
// Every entity listed here is a ledger: rows INSERTed only, never
// UPDATEd or DELETEd. The Data Engine catch-all in
// src/app/api/data/[...path]/route.ts imports this Set and rejects
// PUT/DELETE with a 405 { error: { code: "LEDGER_IMMUTABLE" } }.
//
// The set covers every reachable name a caller might use (entity
// name, table, slug, both cased and lowercase) so a lookup never
// misses because it was keyed the wrong way.
export const APPEND_ONLY_ENTITIES: ReadonlySet<string> = new Set([
]);

export function isAppendOnly(entity: string): boolean {
  if (!entity) return false;
  return APPEND_ONLY_ENTITIES.has(entity)
    || APPEND_ONLY_ENTITIES.has(String(entity).toLowerCase());
}
