/**
 * Event Registry — single source of truth for Data Engine ↔ Workflow Engine bindings.
 *
 * Reads event-bindings.json (generated by contract agent) and wires:
 * - Data Engine mutations → emit events
 * - Workflow Engine → listens for events and triggers workflows
 *
 * All bindings are declarative (JSON) — no code changes needed to add new bindings.
 */

import { onDataEvent } from "@/lib/data-engine";
import type { DataEngineContext } from "@/lib/data-engine";
import { readFileSync, existsSync } from "fs";
import { join } from "path";

// Types
export interface EventBinding {
  event: string;
  source: string;  // "data:<entity>:<operation>" e.g. "data:tasks:create"
  workflows: string[];
  conditions?: EventCondition[];
  description?: string;
}

export interface EventCondition {
  field: string;
  changed?: boolean;
  newValue?: string | number | boolean;
  oldValue?: string | number | boolean;
  operator?: "eq" | "ne" | "in" | "not_in" | "exists";
  values?: (string | number)[];
}

interface BindingsConfig {
  bindings: EventBinding[];
}

// Internal state
let _bindings: EventBinding[] = [];
let _initialized = false;

/**
 * Load bindings from event-bindings.json
 */
export function loadBindings(): EventBinding[] {
  if (_initialized) return _bindings;

  const paths = [
    join(process.cwd(), "src", "contracts", "event-bindings.json"),
    join(process.cwd(), "contracts", "event-bindings.json"),
  ];

  for (const p of paths) {
    if (existsSync(p)) {
      try {
        const raw = readFileSync(p, "utf-8");
        const config: BindingsConfig = JSON.parse(raw);
        _bindings = config.bindings || [];
        _initialized = true;
        console.log(`[EventRegistry] Loaded ${_bindings.length} bindings from ${p}`);
        return _bindings;
      } catch (e) {
        console.error(`[EventRegistry] Failed to parse ${p}:`, e);
      }
    }
  }

  console.log("[EventRegistry] No event-bindings.json found — no bindings active");
  _initialized = true;
  return _bindings;
}

/**
 * Check if an event's conditions are met.
 */
function checkConditions(
  conditions: EventCondition[] | undefined,
  payload: { entity?: Record<string, any>; previousEntity?: Record<string, any> }
): boolean {
  if (!conditions || conditions.length === 0) return true;

  for (const cond of conditions) {
    const current = payload.entity?.[cond.field];
    const previous = payload.previousEntity?.[cond.field];

    if (cond.changed === true && current === previous) return false;

    // An explicit `operator` GOVERNS; the bare newValue/oldValue equality is
    // only a shorthand for when no operator was given.
    //
    // These two lines used to run unconditionally, before the operator was
    // consulted. So for `{ operator: "ne", newValue: X }` the generic check
    // `current !== newValue -> return false` fired in exactly the case where
    // "ne" is supposed to MATCH — the condition could never be true, and every
    // binding using it silently never fired. `eq` worked only because the
    // shorthand happened to agree with it.
    const hasOperator = typeof cond.operator === "string" && cond.operator.length > 0;
    if (!hasOperator) {
      if (cond.newValue !== undefined && current !== cond.newValue) return false;
      if (cond.oldValue !== undefined && previous !== cond.oldValue) return false;
    } else if (cond.oldValue !== undefined && previous !== cond.oldValue) {
      // oldValue is orthogonal to the operator (which compares the NEW value),
      // so it still applies alongside one.
      return false;
    }

    if (cond.operator === "eq" && current !== cond.newValue) return false;
    if (cond.operator === "ne" && current === cond.newValue) return false;
    if (cond.operator === "in" && cond.values && !cond.values.includes(current)) return false;
    if (cond.operator === "not_in" && cond.values && cond.values.includes(current)) return false;
    if (cond.operator === "exists" && (current === null || current === undefined)) return false;
  }

  return true;
}

/**
 * Initialize the event registry — wire Data Engine events to Workflow Engine.
 * Call once at app startup.
 */
export async function initializeEventRegistry(): Promise<void> {
  const bindings = loadBindings();
  if (bindings.length === 0) return;

  // Dynamically import workflow engine
  // Use triggerWorkflow (by id/name): the binding already names the exact target
  // workflow, so start it directly rather than fanning out by event match. It
  // returns the result and persists a task if the workflow pauses at an approval.
  let triggerWorkflow:
    | ((idOrName: string, input: any, user?: any) => Promise<any>)
    | null = null;
  try {
    const wf = await import("@/lib/workflows");
    triggerWorkflow = wf.triggerWorkflow;
  } catch {
    console.log("[EventRegistry] Workflow engine not available — bindings registered but won't trigger");
  }

  // Wire the Data Engine's event emitter to the binding registry
  onDataEvent(async (event: string, payload: any) => {
    // Find all bindings that match this event
    const matching = bindings.filter(b => b.event === event);

    for (const binding of matching) {
      // Check conditions
      if (!checkConditions(binding.conditions, payload)) {
        continue;
      }

      // Trigger each bound workflow directly (persists a task if it pauses).
      for (const workflowId of binding.workflows) {
        if (triggerWorkflow) {
          try {
            await triggerWorkflow(
              workflowId,
              { ...payload, _binding: binding.event, _source: binding.source },
              payload.user,
            );
          } catch (e) {
            console.error(
              `[EventRegistry] Failed to trigger ${workflowId} for ${event}:`, e
            );
          }
        }
      }
    }
  });

  console.log(`[EventRegistry] Wired ${bindings.length} event→workflow bindings`);
}

/**
 * Get all bindings (for UI display / debugging).
 */
export function getBindings(): EventBinding[] {
  if (!_initialized) loadBindings();
  return _bindings;
}

/**
 * Get bindings for a specific entity.
 */
export function getBindingsForEntity(entity: string): EventBinding[] {
  if (!_initialized) loadBindings();
  const slug = entity.toLowerCase();
  return _bindings.filter(b => b.source.includes(`:${slug}:`));
}

/**
 * Get bindings for a specific workflow.
 */
export function getBindingsForWorkflow(workflowId: string): EventBinding[] {
  if (!_initialized) loadBindings();
  return _bindings.filter(b => b.workflows.includes(workflowId));
}
