// AUTO-GENERATED by services/schema_builder.py — do not hand-edit.
//
// SEARCH-1 searchable-columns manifest. Any column declared with
// `search: true` in the plan emits a companion `<name>_search`
// tsvector column (GENERATED ALWAYS AS to_tsvector('english', ...))
// + a GIN index. The Data Engine's op:"search" reads this manifest
// to know WHICH `_search` columns to query per entity.
//
// Values are ORIGINAL plaintext column names — the resolver appends
// `_search` when building the SQL. The manifest is keyed by every
// reachable name a caller might use (entity name / table / slug,
// both cased and lowercase) so a lookup never misses.

export const SEARCHABLE_COLUMNS: Record<string, string[]> = {
};

/** True when the entity has ANY searchable column declared. */
export function hasSearchableColumns(entity: string): boolean {
  if (!entity) return false;
  return !!(SEARCHABLE_COLUMNS[entity]
    || SEARCHABLE_COLUMNS[String(entity).toLowerCase()]);
}

/** Searchable columns for an entity, or [] when none. */
export function searchableColumnsFor(entity: string): string[] {
  if (!entity) return [];
  return SEARCHABLE_COLUMNS[entity]
    || SEARCHABLE_COLUMNS[String(entity).toLowerCase()]
    || [];
}
