// AUTO-GENERATED by services/schema_builder.py — do not hand-edit.
//
// Slice-4 sensitive-columns manifest. The Data Engine reads this at
// both write time (compute masked value + encrypt) and read time
// (mask-by-default; unmask only when the caller's role is in
// `readers` AND the caller passes `unmask: true`).
//
// The manifest is keyed by every reachable name a caller might use
// (entity name / table / slug, both cased and lowercase) so a
// lookup never misses because it was keyed the wrong way.

export type MaskKind = "last4" | "email" | "phone" | "full";

export interface SensitiveColumnSpec {
  /** Mask kind used to compute the pre-computed masked value on write. */
  mask: MaskKind;
  /** Role slugs that may request the full unmasked value.
   * Empty [] = nobody unmasks; ["*"] = every authenticated user.
   */
  readers: string[];
}

export const SENSITIVE_COLUMNS: Record<
  string,
  Record<string, SensitiveColumnSpec>
> = {
};

/** True when the entity has ANY sensitive column declared. */
export function hasSensitiveColumns(entity: string): boolean {
  if (!entity) return false;
  return !!(SENSITIVE_COLUMNS[entity]
    || SENSITIVE_COLUMNS[String(entity).toLowerCase()]);
}

/** Sensitive-column spec map for an entity, or {} when the entity has none. */
export function sensitiveColumnsFor(entity: string): Record<string, SensitiveColumnSpec> {
  if (!entity) return {};
  return SENSITIVE_COLUMNS[entity]
    || SENSITIVE_COLUMNS[String(entity).toLowerCase()]
    || {};
}
