// Auto-generated by schema_pipeline — do not edit by hand.
// Keys are routes (with leading slash). Paths mirror src/schemas/.

import { loadSchema } from "./load";

export const schemas: Record<string, () => Promise<unknown>> = {
  "/documents/[id]": () => import("./documents/[id].json"),
  "/documents/search": () => import("./documents/search.json"),
  "/documents": () => import("./documents.json"),
  "/": () => import("./index.json"),
  "/login": () => import("./login.json"),
  "/shell": () => import("./shell.json"),
};

export async function getSchema(route: string): Promise<ReturnType<typeof loadSchema>> {
  const loader = schemas[route];
  if (!loader) throw new Error(`unknown route '${route}'`);
  const raw = await loader();
  return loadSchema(route, (raw as any).default ?? raw);
}
