"""Seed data for app templates — 15 templates across 8 categories."""

TEMPLATE_SEEDS = [
    # Operations
    {
        "slug": "inventory-manager",
        "name": "Inventory Manager",
        "description": "Track inventory across warehouses with stock levels, reorder points, and movement history.",
        "category": "Operations",
        "icon": "Package",
        "tags": ["inventory", "warehouse", "stock"],
        "complexity": "moderate",
        "relevant_departments": ["Operations", "Warehouse", "Logistics", "Supply Chain", "Procurement"],
        "plan": {
            "tables": ["products", "warehouses", "inventory_items", "stock_movements"],
            "features": [
                "Product catalog with categories and SKUs",
                "Multi-warehouse inventory tracking",
                "Stock movement logging (in/out/transfer)",
                "Low stock alerts and reorder points",
                "Dashboard with stock level overview",
            ],
        },
    },
    {
        "slug": "asset-tracker",
        "name": "Asset Tracker",
        "description": "Manage company assets with assignment tracking, maintenance schedules, and depreciation.",
        "category": "Operations",
        "icon": "Monitor",
        "tags": ["assets", "tracking", "maintenance"],
        "complexity": "moderate",
        "relevant_departments": ["Operations", "IT", "Facilities", "Admin", "Finance"],
        "plan": {
            "tables": ["assets", "asset_categories", "assignments", "maintenance_logs"],
            "features": [
                "Asset catalog with categories and serial numbers",
                "Employee assignment and check-out/check-in",
                "Maintenance schedule tracking",
                "Asset lifecycle and depreciation",
                "Dashboard with asset utilization stats",
            ],
        },
    },
    # Sales
    {
        "slug": "crm-lite",
        "name": "CRM Lite",
        "description": "Lightweight CRM with contacts, deals pipeline, and activity tracking.",
        "category": "Sales",
        "icon": "Users",
        "tags": ["crm", "sales", "pipeline"],
        "complexity": "moderate",
        "relevant_departments": ["Sales", "Business Development", "Account Management", "Revenue"],
        "plan": {
            "tables": ["contacts", "companies", "deals", "activities", "deal_stages"],
            "features": [
                "Contact and company management",
                "Deal pipeline with customizable stages",
                "Activity logging (calls, emails, meetings)",
                "Deal value and win/loss tracking",
                "Pipeline dashboard with conversion metrics",
            ],
        },
    },
    {
        "slug": "quote-builder",
        "name": "Quote Builder",
        "description": "Create and manage sales quotes with line items, pricing, and PDF export.",
        "category": "Sales",
        "icon": "FileText",
        "tags": ["quotes", "pricing", "proposals"],
        "complexity": "moderate",
        "relevant_departments": ["Sales", "Finance", "Account Management", "Pricing"],
        "plan": {
            "tables": ["quotes", "quote_items", "products", "customers"],
            "features": [
                "Quote creation with line items",
                "Product catalog with pricing",
                "Customer management",
                "Quote status tracking (draft, sent, accepted, declined)",
                "Quote summary dashboard",
            ],
        },
    },
    # HR
    {
        "slug": "leave-manager",
        "name": "Leave Manager",
        "description": "Employee leave requests, approvals, and balance tracking.",
        "category": "HR",
        "icon": "Calendar",
        "tags": ["leave", "vacation", "pto"],
        "complexity": "simple",
        "relevant_departments": ["HR", "Human Resources", "People", "People Operations"],
        "plan": {
            "tables": ["employees", "leave_types", "leave_requests", "leave_balances"],
            "features": [
                "Leave request submission with date ranges",
                "Manager approval workflow",
                "Leave balance tracking by type",
                "Team calendar view",
                "Leave summary dashboard",
            ],
        },
    },
    {
        "slug": "employee-directory",
        "name": "Employee Directory",
        "description": "Searchable employee directory with profiles, departments, and org chart.",
        "category": "HR",
        "icon": "UserSearch",
        "tags": ["directory", "employees", "profiles"],
        "complexity": "simple",
        "relevant_departments": ["HR", "Human Resources", "People", "Admin"],
        "plan": {
            "tables": ["employees", "departments", "positions"],
            "features": [
                "Employee profiles with contact info",
                "Department and position management",
                "Search and filter by name, department, position",
                "Organization hierarchy view",
                "Employee count dashboard",
            ],
        },
    },
    # Finance
    {
        "slug": "expense-tracker",
        "name": "Expense Tracker",
        "description": "Submit and approve expense reports with receipt uploads and budget tracking.",
        "category": "Finance",
        "icon": "Receipt",
        "tags": ["expenses", "receipts", "budget"],
        "complexity": "moderate",
        "relevant_departments": ["Finance", "Accounting", "Admin", "Operations"],
        "plan": {
            "tables": ["expense_reports", "expense_items", "categories", "budgets"],
            "features": [
                "Expense report creation with line items",
                "Category-based expense classification",
                "Approval workflow (submit, approve, reject)",
                "Budget tracking by department",
                "Monthly expense summary dashboard",
            ],
        },
    },
    {
        "slug": "invoice-manager",
        "name": "Invoice Manager",
        "description": "Create, send, and track invoices with payment status and aging reports.",
        "category": "Finance",
        "icon": "CreditCard",
        "tags": ["invoices", "billing", "payments"],
        "complexity": "moderate",
        "relevant_departments": ["Finance", "Accounting", "Billing", "Revenue"],
        "plan": {
            "tables": ["invoices", "invoice_items", "customers", "payments"],
            "features": [
                "Invoice creation with line items and tax",
                "Customer management",
                "Payment tracking and status updates",
                "Aging report (30/60/90 days)",
                "Revenue dashboard",
            ],
        },
    },
    # Support
    {
        "slug": "helpdesk",
        "name": "Help Desk",
        "description": "Ticket management system with priorities, assignments, and SLA tracking.",
        "category": "Support",
        "icon": "LifeBuoy",
        "tags": ["tickets", "support", "helpdesk"],
        "complexity": "moderate",
        "relevant_departments": ["Support", "Customer Support", "Customer Success", "IT", "Service"],
        "plan": {
            "tables": ["tickets", "ticket_comments", "categories", "agents"],
            "features": [
                "Ticket creation with priority and category",
                "Agent assignment and workload view",
                "Ticket status workflow (open, in-progress, resolved, closed)",
                "Comment/reply thread on tickets",
                "Ticket metrics dashboard (open, avg resolution time)",
            ],
        },
    },
    {
        "slug": "knowledge-base",
        "name": "Knowledge Base",
        "description": "Internal knowledge base with categories, articles, and search.",
        "category": "Support",
        "icon": "BookOpen",
        "tags": ["knowledge", "docs", "wiki"],
        "complexity": "simple",
        "relevant_departments": ["Support", "Customer Success", "IT", "Training", "Documentation"],
        "plan": {
            "tables": ["articles", "categories", "tags"],
            "features": [
                "Article creation with rich text content",
                "Category and tag organization",
                "Full-text search",
                "Article view count tracking",
                "Recently updated articles dashboard",
            ],
        },
    },
    # IT
    {
        "slug": "server-monitor",
        "name": "Server Monitor",
        "description": "Monitor server health, uptime, and resource usage with alert thresholds.",
        "category": "IT",
        "icon": "Server",
        "tags": ["monitoring", "servers", "alerts"],
        "complexity": "moderate",
        "relevant_departments": ["IT", "Engineering", "DevOps", "Infrastructure", "SRE"],
        "plan": {
            "tables": ["servers", "health_checks", "alerts", "alert_rules"],
            "features": [
                "Server registration with hostname and IP",
                "Health check logging (CPU, memory, disk)",
                "Alert rules with thresholds",
                "Alert history and notifications",
                "Server health dashboard with charts",
            ],
        },
    },
    # Marketing
    {
        "slug": "campaign-tracker",
        "name": "Campaign Tracker",
        "description": "Track marketing campaigns with budgets, channels, and performance metrics.",
        "category": "Marketing",
        "icon": "Megaphone",
        "tags": ["campaigns", "marketing", "analytics"],
        "complexity": "moderate",
        "relevant_departments": ["Marketing", "Growth", "Advertising", "Communications"],
        "plan": {
            "tables": ["campaigns", "channels", "campaign_metrics", "budgets"],
            "features": [
                "Campaign creation with date range and budget",
                "Multi-channel tracking (email, social, ads)",
                "Performance metrics (impressions, clicks, conversions)",
                "Budget allocation and spend tracking",
                "Campaign performance dashboard",
            ],
        },
    },
    {
        "slug": "content-calendar",
        "name": "Content Calendar",
        "description": "Plan and schedule content across channels with status tracking.",
        "category": "Marketing",
        "icon": "CalendarDays",
        "tags": ["content", "calendar", "planning"],
        "complexity": "simple",
        "relevant_departments": ["Marketing", "Content", "Communications", "Social Media"],
        "plan": {
            "tables": ["content_items", "channels", "content_types"],
            "features": [
                "Content item creation with type and channel",
                "Calendar view of scheduled content",
                "Status workflow (draft, review, scheduled, published)",
                "Channel and type filtering",
                "Content pipeline dashboard",
            ],
        },
    },
    # Legal
    {
        "slug": "contract-manager",
        "name": "Contract Manager",
        "description": "Manage contracts with parties, renewal dates, and obligation tracking.",
        "category": "Legal",
        "icon": "Scale",
        "tags": ["contracts", "legal", "compliance"],
        "complexity": "moderate",
        "relevant_departments": ["Legal", "Compliance", "Procurement", "Finance"],
        "plan": {
            "tables": ["contracts", "parties", "obligations", "renewals"],
            "features": [
                "Contract creation with parties and terms",
                "Renewal date tracking with reminders",
                "Obligation and milestone tracking",
                "Contract status management",
                "Expiring contracts dashboard",
            ],
        },
    },
    {
        "slug": "policy-library",
        "name": "Policy Library",
        "description": "Centralized policy document management with versioning and acknowledgment tracking.",
        "category": "Legal",
        "icon": "FileCheck",
        "tags": ["policies", "compliance", "documents"],
        "complexity": "simple",
        "relevant_departments": ["Legal", "Compliance", "HR", "Human Resources", "Admin"],
        "plan": {
            "tables": ["policies", "policy_versions", "acknowledgments", "categories"],
            "features": [
                "Policy creation with categories",
                "Version history tracking",
                "Employee acknowledgment workflow",
                "Search and filter policies",
                "Compliance dashboard (acknowledged vs pending)",
            ],
        },
    },
]
