"""Figma UI Agent — generates ONLY UI files (components, pages, layouts, globals.css).

Used in the Figma relay pipeline where foundation files (package.json, schema,
auth, API routes, etc.) are already generated by prior relay agents.

Wraps the existing run_agent() from agent.py with ui_only=True to constrain
output to visual/UI files only, while preserving the full DESIGN_TO_CODE_PROMPT
system prompt (pixel-perfect rules, styles.json conversion reference, etc.).
"""

import logging
from typing import AsyncIterator

from services.agent_messages import Message

logger = logging.getLogger(__name__)


async def run_figma_ui_agent(
    output_dir: str,
    plan: dict,
    figma_url: str,
    figma_token: str,
) -> AsyncIterator[Message]:
    """Run the Figma design-to-code agent constrained to UI-only output.

    This agent:
    - Reads reference.png and styles.json (pre-fetched)
    - Reads existing foundation files on disk for import paths/types
    - Generates ONLY: globals.css, layouts, components, pages, error/not-found/loading
    - Does NOT create: package.json, tsconfig, schema, auth, API routes, services, etc.

    Yields streaming messages for SSE forwarding.
    """
    from agent import run_agent

    logger.info("[figma_ui] Starting UI-only agent for %s", output_dir)

    async for message in run_agent(
        figma_url=figma_url,
        figma_token=figma_token,
        output_dir=output_dir,
        requirements=plan,
        ui_only=True,
    ):
        yield message

    logger.info("[figma_ui] UI-only agent completed for %s", output_dir)
