import { NextRequest, NextResponse } from "next/server";
import { promises as fs } from "node:fs";
import path from "node:path";
import { resolveProject } from "@/lib/resolveProject";

/**
 * Serve per-project Figma assets from output/<projectId>/public/figma/<file>.
 *
 * Schema Image nodes generated by the Figma MCP transformer use src paths of
 * the form /api/asset/<projectId>/figma/<file> so Next.js can resolve them
 * without requiring a full copy of project assets into the scaffold's own
 * public/ directory.
 */
export async function GET(
  _req: NextRequest,
  { params }: { params: Promise<{ projectId: string; file: string }> },
): Promise<NextResponse> {
  const { projectId, file } = await params;

  // Validate both path segments to prevent directory traversal.
  let projectRoot: string;
  try {
    projectRoot = resolveProject(projectId);
  } catch {
    return new NextResponse("Not found", { status: 404 });
  }

  // Reject any file name that looks like a traversal attempt.
  if (!file || file.includes("/") || file.includes("..") || file.startsWith(".")) {
    return new NextResponse("Not found", { status: 404 });
  }

  const assetPath = path.join(projectRoot, "public", "figma", file);

  let data: Buffer;
  try {
    data = await fs.readFile(assetPath);
  } catch {
    return new NextResponse("Not found", { status: 404 });
  }

  // Derive content-type from extension.
  const ext = path.extname(file).toLowerCase();
  const contentType =
    ext === ".svg"
      ? "image/svg+xml"
      : ext === ".png"
        ? "image/png"
        : ext === ".jpg" || ext === ".jpeg"
          ? "image/jpeg"
          : ext === ".webp"
            ? "image/webp"
            : "application/octet-stream";

  return new NextResponse(data, {
    status: 200,
    headers: {
      "Content-Type": contentType,
      "Cache-Control": "public, max-age=86400, immutable",
    },
  });
}
