/**
 * Requests to this app's own API go under its base path.
 *
 * Inside Forge's Preview the app is served under a prefix
 * (`/api/projects/<id>/preview/serve`). Next.js adds that prefix to links and
 * router pushes, but not to `fetch("/api/...")` — and the SDK, the hooks and
 * the pages all call the app's API that way. Behind the prefix those requests
 * reached Forge itself, so every create, edit and upload in a Preview answered
 * 404 (live, 2026-10-09). With no base path (a deployed app, `next dev`
 * locally) this changes nothing.
 *
 * Installed once, on the client, by a side-effect import in providers.tsx.
 * Auto-generated by Tentoro Forge runtime injector.
 */

const BASE = (process.env.NEXT_PUBLIC_BASE_PATH || "").replace(/\/$/, "");

function prefixed(url: string): string {
  if (!BASE || !url.startsWith("/api/") || url.startsWith(`${BASE}/`)) return url;
  return `${BASE}${url}`;
}

if (typeof window !== "undefined" && BASE) {
  const w = window as typeof window & { __forgeBasePathFetch?: boolean };
  if (!w.__forgeBasePathFetch) {
    w.__forgeBasePathFetch = true;
    const original = window.fetch.bind(window);
    window.fetch = (input: RequestInfo | URL, init?: RequestInit) => {
      if (typeof input === "string") return original(prefixed(input), init);
      if (input instanceof URL) {
        if (input.origin === window.location.origin) {
          const path = prefixed(input.pathname);
          if (path !== input.pathname) {
            return original(new URL(path + input.search + input.hash, input.origin), init);
          }
        }
        return original(input, init);
      }
      if (input instanceof Request) {
        const url = new URL(input.url);
        if (url.origin === window.location.origin) {
          const path = prefixed(url.pathname);
          if (path !== url.pathname) {
            return original(new Request(new URL(path + url.search, url.origin).toString(), input), init);
          }
        }
      }
      return original(input, init);
    };
  }
}

export {};
