/**
 * Catch-all Data API route — handles CRUD for ALL entities via the Data Engine.
 *
 * Routes:
 *   GET    /api/data/[entity]          → list with search/filter/pagination
 *   POST   /api/data/[entity]          → create
 *   GET    /api/data/[entity]/stats    → count
 *   GET    /api/data/[entity]/[id]     → get by id
 *   PUT    /api/data/[entity]/[id]     → update
 *   DELETE /api/data/[entity]/[id]     → delete
 *
 * No per-entity route files needed. The Data Engine handles everything.
 */

import { NextResponse } from "next/server";
import { auth } from "@/auth";
import {
  create, update, remove, findById, query, stats,
  ValidationError, NotFoundError,
  isInitialized, markInitialized, registerEntity,
} from "@/lib/data-engine";
// Slice-3 ledger contract: PUT/DELETE on an append-only entity is rejected
// with 405 { code: "LEDGER_IMMUTABLE" }. The manifest is auto-generated by
// services/schema_builder.py from every plan entity flagged
// `lifecycle: "append_only"` — it always exists (empty Set when the app has
// no ledgers). Rows in these entities are INSERTed only; balances are
// derived from the sum, never stored, so mutating a past row would corrupt
// the derived history.
import { isAppendOnly } from "@/lib/append-only-entities";
// "IT'S REALLY SLOW" HAS TO REACH SOMETHING. Every data operation this route
// runs is timed, and one that takes longer than the app was told to expect is
// reported with WHAT was being done — the operation and the entity — so the
// answer to that sentence can name a screen instead of agreeing that it feels
// slow. What is measured is the handler inside this process and nothing else:
// not the browser's render, not the network, not a cold start before this ran.
import { measured } from "@/lib/error_reporter";
import { PUBLIC_RESOURCES } from "@/lib/public-resources";
import { ENTITY_ACCESS } from "@/lib/entity-access";

/**
 * AN ENTITY IS READ BY THE ROLES ITS PAGES DECLARE. Reception read every user
 * account through this route: the Users page was Admin's, but nothing carried
 * that to the endpoint. The projection lists, per entity, the roles whose
 * pages read it and the roles whose pages are about it; a signed-in role
 * outside the list is refused. An entity the projection does not list stays
 * open to any signed-in role, and a public resource stays open to anyone.
 */
function deniedFor(entity: string | undefined, session: { user?: { role?: unknown } } | null, op: "read" | "write"): boolean {
  if (!entity) return false;
  const access = ENTITY_ACCESS[entity];
  if (!access) return false;
  const roles = access[op] ?? [];
  if (roles.includes("*") && op === "read") return false;
  const role = String(session?.user?.role ?? "");
  if (!session?.user) return !roles.includes("*");
  return !roles.includes(role);
}

// Auto-register all entities on first request
async function ensureInitialized() {
  if (isInitialized()) return;

  // Dynamic import of all schema tables
  const schema = await import("@/db/schema");

  for (const [name, value] of Object.entries(schema)) {
    if (name.endsWith("Relations") || typeof value !== "object" || !value) continue;
    if (typeof value === "function") continue;
    // Drizzle tables have Symbol keys — detect them
    const symbols = Object.getOwnPropertySymbols(value);
    const keys = Object.keys(value as any);
    if (symbols.length === 0 && keys.length === 0) continue;
    // Must have at least one column-like property
    if (keys.length > 0) {
      const firstVal = (value as any)[keys[0]];
      if (!firstVal || typeof firstVal !== "object") continue;
    }
    registerEntity(name, value as any, { slug: name });
  }

  // Wire Data Engine ↔ Workflow Engine via the Event Registry
  try {
    const { initializeEventRegistry } = await import("@/lib/event-registry");
    await initializeEventRegistry();
  } catch {
    // Event registry not available — data engine works standalone without workflows
  }

  markInitialized();
}

function errorResponse(error: unknown) {
  if (error instanceof ValidationError) {
    return NextResponse.json(
      { error: { code: "VALIDATION_ERROR", message: error.message, errors: error.errors } },
      { status: 400 }
    );
  }
  if (error instanceof NotFoundError) {
    return NextResponse.json(
      { error: { code: "NOT_FOUND", message: error.message } },
      { status: 404 }
    );
  }
  if (error instanceof Error && error.message.startsWith("Unknown entity")) {
    return NextResponse.json(
      { error: { code: "NOT_FOUND", message: error.message } },
      { status: 404 }
    );
  }
  console.error("[DataAPI]", error);
  const pgError = error as any;
  if (pgError?.code === "23502") {
    const column = pgError?.column_name || (error instanceof Error ? error.message : "").match(/column "(\w+)"/)?.[1] || "unknown";
    return NextResponse.json(
      { error: { code: "VALIDATION_ERROR", message: `Required field missing: ${column}` } },
      { status: 400 }
    );
  }
  if (pgError?.code === "23505") {
    return NextResponse.json(
      { error: { code: "CONFLICT", message: "A record with this value already exists" } },
      { status: 409 }
    );
  }
  // 22P02 — invalid text representation, i.e. the id in the URL is not the type
  // the id column is. `/api/data/contacts/new` produced this every time a /new
  // page failed to compose: `AppNavigator` fell through to its detail branch and
  // asked for a record named "new", Postgres tried to cast it to uuid, and a
  // routing mistake surfaced as a 500 with a stack trace.
  //
  // AppNavigator no longer does that, and this is the floor underneath it: an id
  // the column cannot even represent is an id no row can have, so the honest
  // answer is 404. A malformed id is a client error; it is not the server
  // failing.
  if (pgError?.code === "22P02") {
    return NextResponse.json(
      { error: { code: "NOT_FOUND", message: "No record with that id" } },
      { status: 404 }
    );
  }
  const message = error instanceof Error ? error.message : "Internal server error";
  return NextResponse.json(
    { error: { code: "INTERNAL_ERROR", message } },
    { status: 500 }
  );
}


/**
 * Whether this resource is reachable without a session.
 *
 * A page declares its own access (§100) and the middleware honours it, so
 * `/plants` rendered for anyone — and then every fetch it made came back 401
 * from here, because this route asked for a session regardless. The plant was
 * in the database and the page that was allowed to show it could not read it.
 *
 * The list is generated from the same derivation the middleware uses: the
 * entities behind a public page's own bindings, and nothing else. An entity
 * only a gated page touches stays gated.
 */
function isPublicResource(entity: string | undefined): boolean {
  return !!entity && PUBLIC_RESOURCES.includes(entity);
}

// ─── Route Handlers ───

export async function GET(
  request: Request,
  { params }: { params: Promise<{ path: string[] }> }
) {
  await ensureInitialized();
  const session = await auth();

  const { path } = await params;
  const [entity, ...rest] = path;
  if (session?.user && deniedFor(entity, session as any, "read")) {
    return NextResponse.json({ error: "Forbidden" }, { status: 403 });
  }
  if (!session?.user && !isPublicResource(entity)) {
    return NextResponse.json({ error: { code: "UNAUTHORIZED" } }, { status: 401 });
  }
  const url = new URL(request.url);
  // Slice-4: `?unmask=accountNumber&unmask=ssn` opts one or more sensitive
  // columns out of masking for THIS request. The data-engine only honours
  // it when the session role is in `readers` for the column — otherwise it
  // silently falls back to the mask. Never a 403 (a UI that speculatively
  // asks for unmask shouldn't get treated as an attack).
  const unmaskColumns = url.searchParams.getAll("unmask");
  // `session` is null on a public resource — the guard above let it through
  // deliberately. The data engine takes an anonymous context; what it must not
  // take is `session.user` off a null.
  const ctx = { user: (session?.user ?? null) as any, unmaskColumns };

  try {
    // GET /api/data/[entity]/stats
    if (rest[0] === "stats") {
      // Same ctx as the list — the count and the rows it counts must agree.
      return NextResponse.json(
        await measured({ operation: "stats", entity }, () => stats(entity, ctx)),
      );
    }

    // GET /api/data/[entity]/[id]
    if (rest[0] && rest[0] !== "stats") {
      const record = await measured({ operation: "read", entity },
                                    () => findById(entity, rest[0], ctx));
      return NextResponse.json(record);
    }

    // GET /api/data/[entity] — list
    const opts = {
      search: url.searchParams.get("search") || undefined,
      filters: Object.fromEntries(
        [...url.searchParams.entries()].filter(([k]) =>
          // `unmask` is a directive, not a filter — must not be applied
          // as a WHERE clause on a non-existent column.
          !["search", "page", "limit", "sort", "order", "unmask"].includes(k)
        )
      ),
      sort: url.searchParams.get("sort") || undefined,
      order: (url.searchParams.get("order") as "asc" | "desc") || "desc",
      page: parseInt(url.searchParams.get("page") || "1"),
      limit: parseInt(url.searchParams.get("limit") || "50"),
    };

    const result = await measured({ operation: "list", entity },
                                  () => query(entity, opts, ctx));
    return NextResponse.json(result);
  } catch (error) {
    return errorResponse(error);
  }
}

export async function POST(
  request: Request,
  { params }: { params: Promise<{ path: string[] }> }
) {
  await ensureInitialized();
  const session = await auth();
  if (!session?.user) {
    return NextResponse.json({ error: { code: "UNAUTHORIZED" } }, { status: 401 });
  }

  const { path } = await params;
  const [entity] = path;
  if (deniedFor(entity, session as any, "write")) {
    return NextResponse.json({ error: "Forbidden" }, { status: 403 });
  }
  const ctx = { user: session.user as any };

  try {
    const body = await request.json();
    const result = await measured({ operation: "create", entity },
                                  () => create(entity, body, ctx));
    return NextResponse.json(result.data, { status: 201 });
  } catch (error) {
    return errorResponse(error);
  }
}

function ledgerImmutableResponse(entity: string) {
  // Slice-3: PUT/DELETE against an append-only entity is a client bug,
  // not a permissions problem — 405 with a code the frontend can branch on.
  return NextResponse.json(
    {
      error: {
        code: "LEDGER_IMMUTABLE",
        message: `Entity "${entity}" is append-only; rows cannot be updated or deleted.`,
        entity,
      },
    },
    { status: 405 },
  );
}

export async function PUT(
  request: Request,
  { params }: { params: Promise<{ path: string[] }> }
) {
  await ensureInitialized();
  const session = await auth();
  if (!session?.user) {
    return NextResponse.json({ error: { code: "UNAUTHORIZED" } }, { status: 401 });
  }

  const { path } = await params;
  const [entity, id] = path;
  if (deniedFor(entity, session as any, "write")) {
    return NextResponse.json({ error: "Forbidden" }, { status: 403 });
  }
  if (!id) {
    return NextResponse.json({ error: { code: "BAD_REQUEST", message: "ID required" } }, { status: 400 });
  }
  if (isAppendOnly(entity)) return ledgerImmutableResponse(entity);
  const ctx = { user: session.user as any };

  try {
    const body = await request.json();
    const result = await measured({ operation: "update", entity },
                                  () => update(entity, id, body, ctx));
    return NextResponse.json(result.data);
  } catch (error) {
    return errorResponse(error);
  }
}

export async function DELETE(
  request: Request,
  { params }: { params: Promise<{ path: string[] }> }
) {
  await ensureInitialized();
  const session = await auth();
  if (!session?.user) {
    return NextResponse.json({ error: { code: "UNAUTHORIZED" } }, { status: 401 });
  }

  const { path } = await params;
  const [entity, id] = path;
  if (deniedFor(entity, session as any, "write")) {
    return NextResponse.json({ error: "Forbidden" }, { status: 403 });
  }
  if (!id) {
    return NextResponse.json({ error: { code: "BAD_REQUEST", message: "ID required" } }, { status: 400 });
  }
  if (isAppendOnly(entity)) return ledgerImmutableResponse(entity);
  const ctx = { user: session.user as any };

  try {
    const result = await measured({ operation: "delete", entity },
                                  () => remove(entity, id, ctx));
    return NextResponse.json(result.data);
  } catch (error) {
    return errorResponse(error);
  }
}
