/**
 * Workflow Execution API Route
 *
 * POST /api/workflows/[id]/execute
 *
 * Body: { input: object, user?: { id, role, email }, taskId?: string }
 * Returns: WorkflowExecutionResult
 *
 * When a workflow pauses at an approval/user_task node, it creates a task
 * record in the workflow_tasks table. To resume, call this endpoint with
 * the taskId and the user's response data in input.
 *
 * Auto-generated by Tentoro Forge runtime injector.
 */

import { NextResponse } from "next/server";
import { triggerWorkflow } from "@/lib/workflows";
import { initializeRuntime } from "@/lib/runtime-loader";
import { db } from "@/db";
import { sql } from "drizzle-orm";
import { auth } from "@/auth";

export async function POST(
  request: Request,
  { params }: { params: Promise<{ id: string }> },
) {
  await initializeRuntime();

  try {
    const { id } = await params;
    const body = await request.json();
    const input = body.input || {};
    // Acting user from the SERVER session (never trust a client-sent user). The
    // workflow runtime defaults owner FKs (ownerId/landlordId/userId/…) from
    // ctx.user.id; without this an authed create hits a NOT NULL FK error.
    const session = await auth();
    const su = session?.user as { id?: string; role?: string; email?: string | null } | undefined;
    const user = su?.id ? { id: su.id, role: su.role, email: su.email ?? undefined } : body.user;
    let taskId = body.taskId;

    // ─── RESUME PATH ──────────────────────────────────────────────────────
    // Any dispatch that carries a taskId (Tasks-inbox completion) OR an
    // entity+__decision (row-level Approve/Reject button) is a resume, not a
    // fresh trigger. Every resume MUST seed the per-node completion markers
    // BEFORE calling triggerWorkflow — the engine walks from the trigger
    // node, and without the marker it re-executes every db_insert / email
    // / http_call upstream of the paused approval, then pauses again
    // (creating a duplicate task row while marking the original completed
    // in the block below). The pre-fix gate was `!taskId` — so the branch
    // that seeded markers was skipped exactly when the Tasks UI sent a
    // taskId, which is the common case. See workflow-audit P0-1.
    let resumeTaskRow: { id: string; node_id: string; process_variables: any } | null = null;
    try {
      if (taskId) {
        const res: any = await db.execute(sql`
          SELECT id, node_id, process_variables
          FROM workflow_tasks
          WHERE id = ${String(taskId)}::uuid
          LIMIT 1
        `);
        resumeTaskRow = (res.rows ?? res)?.[0] ?? null;
      } else if ((input as any).__decision) {
        const entityId = (input as any).entityId ?? (input as any).id ?? null;
        if (entityId) {
          const res: any = await db.execute(sql`
            SELECT id, node_id, process_variables
            FROM workflow_tasks
            WHERE entity_id = ${String(entityId)} AND status = 'pending'
            ORDER BY created_at DESC
            LIMIT 1
          `);
          resumeTaskRow = (res.rows ?? res)?.[0] ?? null;
          if (resumeTaskRow) taskId = resumeTaskRow.id;
        }
      }
    } catch (dbErr) {
      console.warn("[workflow] Could not resolve resume task:", dbErr);
    }

    if (resumeTaskRow) {
      const pv =
        typeof resumeTaskRow.process_variables === "string"
          ? JSON.parse(resumeTaskRow.process_variables || "{}")
          : resumeTaskRow.process_variables || {};
      // Merge order: stored process_variables first, fresh input overrides.
      // Then set completion markers so the engine's short-circuit fires on
      // every already-run node — including the paused approval itself.
      const markers: Record<string, unknown> = {
        [`__step_${resumeTaskRow.node_id}_completed`]: true,
        [`__step_${resumeTaskRow.node_id}_completedBy`]: user?.id ?? null,
      };
      if ((input as any).__decision !== undefined) {
        markers[`__step_${resumeTaskRow.node_id}_decision`] = (input as any).__decision;
        // The user_task/approval node reads `_output` as its returned value;
        // seed the decision here so downstream conditions can gate on it via
        // outputMappings without an entity re-query.
        markers[`__step_${resumeTaskRow.node_id}_output`] = { decision: (input as any).__decision };
      }
      Object.assign(input, { ...pv, ...input, ...markers });
    }

    // Detached mode (?detach=1): kick off the workflow and return immediately
    // so a "Queue for processing" button in the UI can navigate to the list
    // page instantly instead of blocking for the whole pipeline (which
    // includes OCR + Claude vision — 30-45s). Errors surface later on the
    // detail page (status=failed + errorMessage), not in the initial POST.
    const url = new URL(request.url);
    const detach = url.searchParams.get("detach") === "1";
    if (detach) {
      void triggerWorkflow(id, input, user).catch((err) => {
        console.error("[workflow] detached run failed:", err);
      });
      return NextResponse.json(
        { status: "queued", workflowId: id, mode: "detached" },
        { status: 202 },
      );
    }

    // triggerWorkflow persists a pending task itself if the workflow pauses.
    const result = await triggerWorkflow(id, input, user);

    // If resuming a completed task: update the task record
    if (taskId) {
      try {
        await db.execute(sql`
          UPDATE workflow_tasks
          SET status = 'completed',
              completed_by = ${user?.id || null},
              completed_at = NOW(),
              decision = ${input.__decision || null},
              response_data = ${JSON.stringify(input)}
          WHERE id = ${taskId}::uuid
        `);
      } catch (dbErr) {
        console.warn("[workflow] Could not update task:", dbErr);
      }
    }

    return NextResponse.json(result);
  } catch (error) {
    return NextResponse.json(
      { error: error instanceof Error ? error.message : String(error) },
      { status: 500 },
    );
  }
}
